### ISSUE TITLE
How to config smtps(port 465) in the file of git-notifier-config.yml

### ISSUE THREAD

**Issue by Donny2333** [git-commit-notifier/git-commit-notifier#217]
I want to connect 163 mail server. And I try this:

```
smtp_server:
  address: smtp.163.com
  port: 465
  domain: smtp.163.com
  user_name: *USERNAME*@163.com
  password: *HERE_IS_PW*
  authentication: login
  enable_tls: true
```

But, It cannot connect to the smtp port of 163.com, It shows:

```
remote: Sending mail...
remote: /usr/local/rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks: end of file reached (EOFError)
```

Is because I missing something like **nss-config-dir**?
